//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class favorite_log
    {
        public int fav_log_id { get; set; }
        public int fav_id { get; set; }
        public int user_id { get; set; }
        public string artist_name { get; set; }
        public string song_name { get; set; }
        public string song_deezer { get; set; }
        public string song_spotify { get; set; }
        public System.DateTime date_add { get; set; }
        public string wikipedia_entry { get; set; }
    }
}
