//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pushmusicwebEntities : DbContext
    {
        public pushmusicwebEntities()
            : base("name=pushmusicwebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<favorite> favorite { get; set; }
        public DbSet<favorite_log> favorite_log { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<users_log> users_log { get; set; }
    }
}
